# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-pikavirus-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.9.4   # o es 3.9.1?
  - conda-forge::markdown=3.3.4
  - conda-forge::pymdown-extensions=8.2
  - conda-forge::pygments=2.9.0
  - conda-forge::numpy=1.20.2
  - conda-forge::matplotlib-base=3.4.2
  - conda-forge::pandas=1.2.4
  - conda-forge::biopython=1.78
  - conda-forge::tbb=2021.2.0

  - bioconda::nextflow=21.04.0
  - bioconda::fastqc=0.11.9
  - bioconda::fastp=0.20.1
  - bioconda::samtools=1.12
  - bioconda::bedtools=2.30.0
  - bioconda::multiqc=1.10.1
  - bioconda::kraken2=2.1.2
  - bioconda::bowtie2=2.4.2
  - bioconda::spades=3.15.2
  - bioconda::quast=5.0.2 
  - bioconda::kaiju=1.7.4
  - bioconda::mash=2.3
  - bioconda::krona=2.8