# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: PikaVirus_dev

channels:
  - bioconda
  - conda-forge
  - defaults
  - plotly

dependencies:
  - bioconda::bedtools=2.30.0
  - bioconda::bowtie2=2.4.4
  - bioconda::fastp=0.20.1
  - bioconda::fastqc=0.11.9
  - bioconda::ivar=1.3.1
  - bioconda::kaiju=1.7.4
  - bioconda::kraken2=2.1.2
  - bioconda::krona=2.8
  - bioconda::mash=2.3
  - bioconda::multiqc=1.9
  - bioconda::muscle=3.8.31
  - bioconda::quast=5.0.2 
  - bioconda::samtools=1.12
  - bioconda::spades=3.14.0
  - conda-forge::biopython=1.78
  - conda-forge::markdown=3.2.2
  - conda-forge::numpy=1.19.5
  - conda-forge::pandas=1.1.5
  - conda-forge::pygments=2.6.1
  - conda-forge::pymdown-extensions=7.1
  - conda-forge::python=3.6.10
  - conda-forge::tbb=2020.2
  - plotly=4.14.3=py_0
